#!/usr/bin/env python3
"""
Download the official ZhihuRec release and materialize a local ZhihuRec-1M subset.

The upstream README states that ZhihuRec-20M and ZhihuRec-1M can be generated by
taking the top N lines from each of the eight released files. This helper keeps
the raw release and the derived subset in separate directories.
"""

from __future__ import annotations

import argparse
import gzip
import json
import shutil
import sys
import urllib.request
from pathlib import Path


SHARE_TOKEN = "d6c045c55aa14bb39ebc"
BASE_URL = f"https://cloud.tsinghua.edu.cn/d/{SHARE_TOKEN}/files/"
ROOT = Path(__file__).resolve().parents[2]
RAW_ROOT = ROOT / "data" / "raw" / "zhihurec"
SOURCE_DIR = RAW_ROOT / "source"
ONE_M_DIR = RAW_ROOT / "1m"

SOURCE_FILES = {
    "inter_impression.csv.gz": {
        "path": "/inter_impression.csv.gz",
        "size": 672_366_803,
        "subset_lines": 999_970,
    },
    "inter_query.csv.gz": {
        "path": "/inter_query.csv.gz",
        "size": 29_753_340,
        "subset_lines": 38_422,
    },
    "info_user.csv.gz": {
        "path": "/info_user.csv.gz",
        "size": 55_899_286,
        "subset_lines": 7_974,
    },
    "info_answer.csv.gz": {
        "path": "/info_answer.csv.gz",
        "size": 376_276_412,
        "subset_lines": 81_563,
    },
    "info_question.csv.gz": {
        "path": "/info_question.csv.gz",
        "size": 6_472_504,
        "subset_lines": 29_340,
    },
    "info_author.csv.gz": {
        "path": "/info_author.csv.gz",
        "size": 872_869,
        "subset_lines": 47_888,
    },
    "info_topic.csv.gz": {
        "path": "/info_topic.csv.gz",
        "size": 154_271,
        "subset_lines": 22_897,
    },
    "info_token.csv.gz": {
        "path": "/info_token.csv.gz",
        "size": 172_321_037,
        "subset_lines": 249_586,
    },
}

UPSTREAM = {
    "github": "https://github.com/THUIR/ZhihuRec-Dataset",
    "cloud_share": f"https://cloud.tsinghua.edu.cn/d/{SHARE_TOKEN}/",
    "paper": "https://arxiv.org/abs/2106.06467",
}


def _download_url(remote_path: str) -> str:
    quoted = urllib.request.quote(remote_path)
    return f"{BASE_URL}?p={quoted}&dl=1"


def _ensure_dirs() -> None:
    SOURCE_DIR.mkdir(parents=True, exist_ok=True)
    ONE_M_DIR.mkdir(parents=True, exist_ok=True)


def _download_file(name: str, remote_path: str, expected_size: int, force: bool) -> Path:
    destination = SOURCE_DIR / name
    if destination.exists() and destination.stat().st_size == expected_size and not force:
        print(f"[skip] {name} already present")
        return destination

    if destination.exists() and force:
        destination.unlink()

    url = _download_url(remote_path)
    print(f"[download] {name}")
    with urllib.request.urlopen(url) as response, destination.open("wb") as handle:
        shutil.copyfileobj(response, handle, length=1024 * 1024)

    actual_size = destination.stat().st_size
    if actual_size != expected_size:
        raise RuntimeError(f"{name} size mismatch: expected {expected_size}, got {actual_size}")
    return destination


def _take_top_lines(src: Path, dest: Path, limit: int) -> None:
    written = 0
    with gzip.open(src, "rt", encoding="utf-8", errors="replace") as reader:
        with dest.open("w", encoding="utf-8") as writer:
            for written, line in enumerate(reader, start=1):
                writer.write(line)
                if written >= limit:
                    break

    if written != limit:
        raise RuntimeError(f"{src.name} ended early: expected {limit} lines, got {written}")


def _build_subset(force: bool) -> dict[str, dict[str, int | str]]:
    manifest_files: dict[str, dict[str, int | str]] = {}
    for name, meta in SOURCE_FILES.items():
        src = SOURCE_DIR / name
        if not src.exists():
            raise FileNotFoundError(f"Missing source file: {src}")

        output_name = name.removesuffix(".gz")
        dest = ONE_M_DIR / output_name
        if dest.exists() and not force:
            line_count = sum(1 for _ in dest.open("r", encoding="utf-8"))
            if line_count == meta["subset_lines"]:
                print(f"[skip] {output_name} already prepared")
                manifest_files[output_name] = {
                    "source": str(src.relative_to(ROOT)),
                    "target_lines": meta["subset_lines"],
                    "actual_lines": line_count,
                }
                continue

        print(f"[prepare] {output_name}")
        _take_top_lines(src, dest, int(meta["subset_lines"]))
        line_count = sum(1 for _ in dest.open("r", encoding="utf-8"))
        manifest_files[output_name] = {
            "source": str(src.relative_to(ROOT)),
            "target_lines": meta["subset_lines"],
            "actual_lines": line_count,
        }

    manifest = {
        "dataset": "ZhihuRec-1M",
        "description": "Locally derived by taking the top N lines from the official ZhihuRec release files.",
        "sources": UPSTREAM,
        "files": manifest_files,
    }
    manifest_path = ONE_M_DIR / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return manifest


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--skip-download",
        action="store_true",
        help="Assume the official compressed files are already present in data/raw/zhihurec/source.",
    )
    parser.add_argument(
        "--download-only",
        action="store_true",
        help="Download the official compressed files but do not materialize the 1M subset.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-download or rebuild outputs even if they already exist.",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    _ensure_dirs()

    if not args.skip_download:
        for name, meta in SOURCE_FILES.items():
            _download_file(name, str(meta["path"]), int(meta["size"]), force=args.force)

    if not args.download_only:
        manifest = _build_subset(force=args.force)
        print("[done] prepared ZhihuRec-1M")
        print(json.dumps(manifest["files"], ensure_ascii=False, indent=2))
    else:
        print("[done] downloaded official ZhihuRec source files")

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
